# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: Install git-mob # runs during prebuild
    command: npm i -g git-mob
vscode:
  extensions:
    - redhat.java
    - mhutchie.git-graph